/**
 * test/integration/doc.test.js
 * `decode doc` end-to-end against a hermetic mock LLM server
 * (OpenAI-compatible /v1/chat/completions). The CLI child runs in a temp
 * project configured via `decode connect`; no real LLM, no real keys.
 */
import { describe, it, expect, beforeAll, afterAll, beforeEach, afterEach } from 'vitest';
import { execa } from 'execa';
import http from 'node:http';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const CLI = fileURLToPath(new URL('../../bin/decode.js', import.meta.url));
const CANNED_DOC = '# Canned Architecture\n\nGenerated by the mock LLM.';
const CANNED_EXPLAIN = 'This project is a demo CLI.';

let server;
let baseUrl;
let tmp;

beforeAll(async () => {
  server = http.createServer((req, res) => {
    res.writeHead(200, { 'content-type': 'application/json' });
    if (req.url === '/v1/chat/completions') {
      let body = '';
      req.on('data', (chunk) => {
        body += chunk;
      });
      req.on('end', () => {
        const isArchitecture = (body || '').includes('Doc Generator');
        res.end(
          JSON.stringify({
            choices: [{ message: { content: isArchitecture ? CANNED_DOC : CANNED_EXPLAIN } }],
          }),
        );
      });
    } else {
      res.end(JSON.stringify({ error: 'not found' }));
    }
  });
  await new Promise((resolve) => server.listen(0, '127.0.0.1', resolve));
  baseUrl = `http://127.0.0.1:${server.address().port}`;
});

afterAll(() => {
  server.closeAllConnections?.();
  return new Promise((resolve) => server.close(resolve));
});

beforeEach(() => {
  tmp = fs.mkdtempSync(path.join(os.tmpdir(), 'decode-doc-it-'));
  // minimal project for the scanner + staleness check
  fs.mkdirSync(path.join(tmp, 'src'), { recursive: true });
  fs.writeFileSync(path.join(tmp, 'package.json'), '{"name":"demo","version":"1.0.0"}');
  fs.writeFileSync(path.join(tmp, 'src', 'index.js'), 'console.log("hi");');
});

afterEach(() => {
  fs.rmSync(tmp, { recursive: true, force: true });
});

function run(args, opts = {}) {
  return execa(process.execPath, [CLI, ...args], {
    cwd: tmp,
    reject: false,
    env: { LLM_PROVIDER_BASE_URL: baseUrl },
    ...opts,
  });
}

/** Configures the temp project's LLM provider/key via the real `connect` flow. */
async function configureLlm() {
  const connect = await run(['connect', 'fake-key', '--provider', 'openai']);
  expect(connect.exitCode).toBe(0);
}

describe('decode doc (generate)', () => {
  it('writes docs/architecture.md after --yes approval', async () => {
    await configureLlm();
    const doc = await run(['doc', '--yes']);
    expect(doc.exitCode).toBe(0);
    const outPath = path.join(tmp, 'docs', 'architecture.md');
    expect(fs.existsSync(outPath)).toBe(true);
    expect(fs.readFileSync(outPath, 'utf8')).toContain('Architecture');
  });

  it('honors --dry-run: previews without writing anything', async () => {
    await configureLlm();
    const doc = await run(['doc', '--dry-run']);
    expect(doc.exitCode).toBe(0);
    expect(fs.existsSync(path.join(tmp, 'docs', 'architecture.md'))).toBe(false);
  });

  it('accepts a guidance message (AC2)', async () => {
    await configureLlm();
    const doc = await run(['doc', 'focus on the CLI entry point', '--yes']);
    expect(doc.exitCode).toBe(0);
    expect(fs.existsSync(path.join(tmp, 'docs', 'architecture.md'))).toBe(true);
  });

  it('fails clearly when no LLM is configured', async () => {
    const doc = await run(['doc', '--yes']);
    expect(doc.exitCode).toBe(1);
    expect(doc.stderr.toLowerCase()).toContain('llm');
  });
});

describe('decode doc --explain (read-only)', () => {
  it('prints the explanation and writes nothing', async () => {
    await configureLlm();
    const explain = await run(['doc', '--explain']);
    expect(explain.exitCode).toBe(0);
    expect(explain.stdout).toContain('demo CLI');
    expect(fs.existsSync(path.join(tmp, 'docs'))).toBe(false);
  });

  it('fails clearly when no LLM is configured', async () => {
    const explain = await run(['doc', '--explain']);
    expect(explain.exitCode).toBe(1);
    expect(explain.stderr.toLowerCase()).toContain('llm');
  });
});

describe('decode doc check (staleness)', () => {
  function writeDoc() {
    fs.mkdirSync(path.join(tmp, 'docs'), { recursive: true });
    fs.writeFileSync(path.join(tmp, 'docs', 'architecture.md'), '# Docs');
  }

  it('exits 0 when docs are fresh', async () => {
    writeDoc();
    // src/index.js was written in beforeEach, before docs — docs are newest
    const check = await run(['doc', 'check']);
    expect(check.exitCode).toBe(0);
    expect(check.stdout.toLowerCase()).toContain('up to date');
  });

  it('exits 1 and lists the changed source when stale', async () => {
    writeDoc();
    fs.writeFileSync(path.join(tmp, 'src', 'index.js'), 'console.log("changed");');
    // bump src mtime past docs
    const future = new Date(Date.now() + 5000);
    fs.utimesSync(path.join(tmp, 'src', 'index.js'), future, future);

    const check = await run(['doc', 'check']);
    expect(check.exitCode).toBe(1);
    expect(check.stderr).toContain('src/index.js');
  });

  it('emits valid JSON with --json', async () => {
    const check = await run(['doc', 'check', '--json']);
    expect(check.exitCode).toBe(1); // no docs → stale
    const parsed = JSON.parse(check.stdout);
    expect(parsed).toHaveProperty('stale');
    expect(parsed).toHaveProperty('staleSources');
  });
});
